spring.application.name=carshop
spring.config.import=optional:file:.env[.properties]

# MySQL Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/carshop_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# Cloudinary Configuration
cloudinary.cloud-name=diamce7e1
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# File Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB

# Giao Hang Nhanh
ghn.token=${GHN_TOKEN:}
ghn.shop-id=${GHN_SHOP_ID:}
ghn.api-url=${GHN_API_URL:https://dev-online-gateway.ghn.vn/shiip/public-api/v2}
